### PR TITLE
Added constructor overload to DaClient

### PR DESCRIPTION
**Pull request by swebgit**
Addresses issue #69

### CODE REVIEW

**Comment by jmbeach** [comment]
I'd prefer that the new constructor accepts a URL instead of a string.

**Comment by jmbeach** [comment]
Awesome. The only other thing is that you may be able to take out the suppression message now.

**Comment by swebgit** [comment]
Yup, I already did take out the suppression. I also had to add a reference to `OpcNetApi.dll` in the CLI project in order to get it to build.

**Comment by jmbeach** [comment]
Ok, awesome. Thanks for your contribution.

**Pull request merged**
